# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update JSON

on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Dump All LSG Bodies
      run: |
        rm -r data/*
        python lsg.py
    - name: Commit files
      run: |
          git config --global user.name 'Maintainer'
          git config --global user.email '57325503+shrihari689@users.noreply.github.com'
          git add .
          git commit -m "Update JSON 🌍"
          git push
